#!/bin/sh

echo "keytool will request the following information:"
cat <<EOF
What is your first and last name?
  [Unknown]:  Name
What is the name of your organizational unit?
  [Unknown]:  Organization Unit Name
What is the name of your organization?
  [Unknown]:  Organization Name
What is the name of your City or Locality?
  [Unknown]:  Huntsville
What is the name of your State or Province?
  [Unknown]:  AL
What is the two-letter country code for this unit?
  [Unknown]:  US
Is CN=Name, OU=Organization Unit Name, O=Organization Name, L="Huntsville, AL", ST=AL, C=US correct?
  [no]:  yes

Enter key password for <selfsigned>
	(RETURN if same as keystore password):  
Re-enter new password: 
EOF
echo "Key password should be 'keyPass'."

keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore -storepass keystorePass -validity 360 -keysize 2048 -v
